FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package.json ./
COPY frontend/yarn.lock* ./

RUN yarn install

COPY frontend/ .

# HARDKODIRANO - tvoj IP
ENV REACT_APP_BACKEND_URL=http://76.13.6.233

RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]